spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/triage}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password@1}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.pathmatch.use-suffix-pattern=false
server.port=${PORT:8080}
